language: generic
sudo: true
dist: xenial

env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14/bin:$PATH

before_install:
  - sudo add-apt-repository ppa:jgross-h/many-coq-versions --yes
  - sudo add-apt-repository ppa:hvr/ghc --yes
  - sudo apt-get update
  - sudo apt-get install coq-8.9.0 ghc-8.6.5 clang --yes
  - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
  - tar xzf riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
  - git clone https://github.com/riscv/riscv-tests
  - cd riscv-tests && git submodule update --init --recursive && autoconf && ./configure --prefix=$TRAVIS_BUILD_DIR/riscv && sed -i -e "s/0x80000000/00000000/g" ./env/p/link.ld && make -j && make install && cd ..
  - git clone http://git.veripool.org/git/verilator
  - cd verilator && autoconf && ./configure && make -j && sudo make install && cd .. && rm -rf verilator

install:
  - make -j

jobs:
  include:
  - script: ./createObjDir.sh 32 && ./runElf.sh $TRAVIS_BUILD_DIR/riscv/target/share/riscv-tests/isa/rv32ui-p-add
  - script: ./createObjDir.sh 64 && ./runElf.sh $TRAVIS_BUILD_DIR/riscv/target/share/riscv-tests/isa/rv64ui-p-add

