language: generic
sudo: true
dist: xenial

env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14/bin:$PATH

before_install:
  - sudo add-apt-repository ppa:jgross-h/many-coq-versions --yes
  - sudo add-apt-repository ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install coq-8.9.0 ghc-8.6.5 clang
  - git clone http://git.veripool.org/git/verilator
  - cd verilator && autoconf && ./configure && make -j 4 && sudo make install && cd ..
  - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
  - tar xzf riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
  - git clone https://github.com/riscv/riscv-tests
  - cd riscv-tests && git submodule update --init --recursive && autoconf && ./configure --prefix=$TRAVIS_BUILD_DIR/riscv && sed -i -e "s/0x80000000/00000000/g ./env/p/link.ld && "make && make install

install:
  - cat > Target.hs <<- EOF \
  module Target (module Syntax, module Rtl, module Word, module Fin, module EclecticLib, module PeanoNat, rtlMod) where\
  import EclecticLib\
  import PeanoNat\
  import Fin\
  import Instance\
  import Rtl\
  import Syntax hiding (unsafeCoerce)\
  import Word\
  rtlMod :: RtlModule\
  rtlMod = model32\
  EOF
#  - ghc -j + RTS -A128m -n4m -O0 --make -o Print32 Kami/PrettyPrintVerilog.hs
#  - ./Print32 > System.sv
#  - verilator --top-module system -Wno-CMPCONST -O0 -Wno-WIDTH --cc System.sv --trace --trace-underscore -Wno-fatal --exe System.cpp
#  - make -j -C obj_dir -f Vsystem.mk Vsystem CXX=clang LINK=clang
#  - mv obj_dir obj_dir32
#  - cat > Target.hs <<- EOF \
#  module Target (module Syntax, module Rtl, module Word, module Fin, module EclecticLib, module PeanoNat, rtlMod) where\
#  import EclecticLib\
#  import PeanoNat\
#  import Fin\
#  import Instance\
#  import Rtl\
#  import Syntax hiding (unsafeCoerce)\
#  import Word\
#  rtlMod :: RtlModule\
#  rtlMod = model64\
#  EOF
#  - ghc -j + RTS -A128m -n4m -O0 --make -o Print64 Kami/PrettyPrintVerilog.hs
#  - ./Print64 > System.sv
#  - verilator --top-module system -Wno-CMPCONST -O0 -Wno-WIDTH --cc System.sv --trace --trace-underscore -Wno-fatal --exe System.cpp
#  - make -j -C obj_dir -f Vsystem.mk Vsystem CXX=clang LINK=clang
#  - mv obj_dir obj_dir64
#
#jobs:
#  include:
#  - mv obj_dir32 obj_dir && ./runElf.sh $TRAVIS_BUILD_DIR/riscv/target/share/riscv-tests/isa/rv32ui-p-add && mv obj_dir obj_dir32
#  - mv obj_dir64 obj_dir && ./runElf.sh $TRAVIS_BUILD_DIR/riscv/target/share/riscv-tests/isa/rv64ui-p-add && mv obj_dir obj_dir64
#
