language: coq
sudo: enabled
before_install:
  - sudo apt update -qq
  - yes '' | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
  - yes | opam init --disable-sandboxing --reinit
  - opam --version
  - yes | opam repo add coq-released http://coq.inria.fr/opam/released --set-default
  - opam switch create ocaml --yes
  - eval $(opam env)
  - opam install coq.8.9.0 --yes
  - eval $(opam env)
install:
  - make 
script:
  - ./runTests.sh -v -x 32 -p riscv-tests
  - ./runTests.sh -v -x 64 -p riscv-tests
