language: coq
sudo: enabled
before_install:
  - sudo apt update -qq
  - sudo apt install clang
  - wget https://downloads.haskell.org/~ghc/8.6.4/ghc-8.6.4-x86_64-deb9-linux.tar.xz && tar -xvf ghc-8.6.4-x86_64-deb9-linux.tar.xz && cd ghc-8.6.4 && ./configure && sudo make install
  - cd ~
  - git clone http://git.veripool.org/git/verilator && cd verilator && autoconf && ./configure && sudo make install
  - cd ~
  - yes '' | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
  - yes | opam init --disable-sandboxing --reinit
  - opam --version
  - yes | opam repo add coq-released http://coq.inria.fr/opam/released --set-default
  - opam switch create ocaml --yes
  - eval $(opam env)
  - opam install coq.8.9.0 --yes
  - eval $(opam env)
  - cd ~
  - ls
  - pwd
  - cd sifive/RiscvSpecFormal
install:
  - make 
script:
  - ./runTests.sh -v -x 32 -p riscv-tests
  - ./runTests.sh -v -x 64 -p riscv-tests
