language: generic
cache:
  directories:
    - ~/coq-object-files
jobs:
  include:
  - stage: coqcompile
    before_install:
      - sudo apt update

      # Opam
      - sudo apt install opam
      - yes '' | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
      - yes | opam init --disable-sandboxing --reinit
      - yes | opam repo add coq-released http://coq.inria.fr/opam/released --set-default
      - opam switch create ocaml --yes
      - eval $(opam env)

      # Coq
      - opam install coq.8.9.0 --yes
      - eval $(opam env)

    script:
      - make
      - rm -rf ~/coq-object-files
      - cp -rf $TRAVIS_BUILD_DIR ~/coq-object-files

  - stage: rvtests
    before_install:
      - sudo apt update

      # RISC-V compiler
      - cd ~
      - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
      - tar -xzf riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
      - export PATH=$PATH:$(pwd)/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14/bin
      - cd $TRAVIS_BUILD_DIR

      # Clang
      - sudo apt install clang-3.5

      # GHC
      - sudo apt install ghc
      - sudo apt install cabal-install
      - cabal update
      - cabal install mtl-2.2.2

      # Verilator
      - cd ~
      - git clone http://git.veripool.org/git/verilator
      - cd verilator
      - autoconf
      - ./configure
      - sudo make install

    script:
      - cd ~/coq-object-files
      - ./runTests.sh -v -k -g -t -x 32 -p riscv-tests

  - stage: rvtests
    before_install:
      - sudo apt update

      # RISC-V compiler
      - cd ~
      - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
      - tar -xzf riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14.tar.gz
      - export PATH=$PATH:$(pwd)/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14/bin
      - cd $TRAVIS_BUILD_DIR

      # Clang
      - sudo apt install clang-3.5

      # GHC
      - sudo apt install ghc
      - sudo apt install cabal-install
      - cabal update
      - cabal install mtl-2.2.2

      # Verilator
      - cd ~
      - git clone http://git.veripool.org/git/verilator
      - cd verilator
       autoconf
      - ./configure
      - sudo make install

    script:
      - cd ~/coq-object-files
      - ./runTests.sh -v -k -g -t -x 64 -p riscv-tests
