language: generic
sudo: true
dist: xenial

cache:
  directories:
  - $HOME/haskell-files
  - $HOME/verilator-binary

env:
  global:
  - PATH=/opt/ghc/bin:$HOME/verilator-binary/bin:$TRAVIS_BUILD_DIR/riscv64-unknown-elf-gcc-8.2.0-2019.02.0-x86_64-linux-ubuntu14/bin:$PATH

jobs:
  include:
  - stage: generate_verilator_binary_and_haskell_files

    script:
    - git clone http://git.veripool.org/git/verilator && cd verilator && autoconf && ./configure --prefix=$HOME/verilator-binary && make -j 4 && make install && cd .. && rm -rf verilator

  - script:
    - sudo add-apt-repository ppa:jgross-h/many-coq-versions --yes
    - sudo apt-get update
    - sudo apt-get install coq-8.9.0 --yes
    - make -j 4
    - rm -rf $HOME/haskell-files/*
    - mkdir -p $HOME/haskell-files
    - cp *.hs $HOME/haskell-files/

  - stage: run_tests
    script:
    - ./.travis.sh 32
    - echo $PATH
    - ls $HOME/haskell-files
    - ls $HOME/verilator-binary
    - ls $HOME/riscv
    - ghc --version
  - script: ./.travis.sh 32
  - script: ./.travis.sh 64
